//const host = 'http://localhost:5000';
//const host = `https://ninchatapi.onrender.com`;
const host = `http://localhost:4100`; // rest api url 
export const socketHost = `localhost:4300`; // socket url
const authRoute = `${host}/api/auth`;
export const registerRoute = `${authRoute}/register`;
export const loginRoute = `${authRoute}/login`;
export const setAvatarRoute = `${authRoute}/setAvatar`;
export const usersRoute = `${authRoute}/users`;
export const messagesRoute = `${authRoute}/messages`;
