//const host = 'http://localhost:5000';
//const host = `https://ninchatapi.onrender.com`;
const host = process.env.REACT_APP_API_URL; // rest api url 
export const socketHost = process.env.REACT_APP_SOCKET_URL; // socket url
const authRoute = `${host}/api/auth`;
export const registerRoute = `${authRoute}/register`;
export const loginRoute = `${authRoute}/login`;
export const setAvatarRoute = `${authRoute}/setAvatar`;
export const usersRoute = `${authRoute}/users`;
export const messagesRoute = `${authRoute}/messages`;
